language: r
dist: trusty
sudo: required
# warnings_are_errors: true

cache: packages   # to rebuild cache see tweet thread ending here https://twitter.com/jimhester_/status/1115718589804421121

# Specify here which R version to run

r:
  - oldrel
  - release
  - devel

# Check test coverage for badge on Github Page / Deploy pkgdown website to Github Pages

r_packages:
  - covr # used for code coverage reports in github pull requests

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

# Keep posted on errors

notifications:
  email:
    on_success: never
    on_failure: never
