# Run this workflow whenever there is a push or pull request to the repository
on: pull_request #default to types [opened, synchronize, reopened] # [push, pull_request]


# Name of the workflow
name: check-and-test-pull-request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job for test on ubunutu only
  tests-ubuntu-16-04-R-3-6:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # to install binaries on ubuntu
      RSPM: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6
      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install package dependencies
        # RcppGSL and stringi can currently not load or link when installed from RSPM,
        #   therefore install from cran (source)
        run: |
          remotes::install_deps(dependencies = TRUE)
          print(getOption("repos"))
          remotes::install_cran("testthat", repos = "https://cran.rstudio.com/")
          remotes::install_cran("devtools", repos = "https://cran.rstudio.com/")
          remotes::install_cran("covr", repos = "https://cran.rstudio.com/")
        shell: Rscript {0}
        
      - name: Run tests
        run: | 
          library(testthat)
          library(devtools)
          devtools::test(reporter=RstudioReporter)
        shell: Rscript {0}
      
      - name: Test coverage, if tests succeeded
        if: success()
        # run: covr::codecov()
        run: covr::package_coverage(type = "tests", quiet = FALSE)
        shell: Rscript {0}


  # job for R CMD checks on win, mac, ubuntu
  R-CMD-check-win-mac-ubuntu-R362:
    runs-on: ${{ matrix.config.os }}
    name: R-CMD-check-win-mac-ubuntu-R362-${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6.2'}
          - {os: macOS-latest,  r: '3.6.2'}
          - {os: ubuntu-16.04, r: '3.6.2', rspm: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
    env:
        R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        RSPM: ${{ matrix.config.rspm }}

    steps:
        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-r@master
          with:
            r-version: ${{ matrix.config.r }}

        - name: Query dependencies
          run: |
            install.packages('remotes')
            saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
          shell: Rscript {0}

        - name: Cache R packages
          if: runner.os != 'Windows'
          uses: actions/cache@v1
          with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
            restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

        - name: Install system dependencies
          if: runner.os == 'Linux'
          env:
            RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
          run: |
            Rscript -e "remotes::install_github('r-hub/sysreqs')"
            sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
            sudo -s eval "$sysreqs"

        - name: Install dependencies, some from cran incl RcppGSL and stringi
          run: |
            remotes::install_deps(dependencies = TRUE)
            remotes::install_cran("rcmdcheck")
            if(file.exists('depends.Rds')) {file.remove('depends.Rds')}
          shell: Rscript {0}

        - name: Check
          run: rcmdcheck::rcmdcheck(args = c("--no-tests", "--as-cran", "--no-manual"), error_on = "warning", check_dir = "check")
          shell: Rscript {0}

        - name: Upload check results
          if: failure()
          uses: actions/upload-artifact@master
          with:
            name: R-CMD-check-results-${{ runner.os }}-r${{ matrix.config.r }}
            path: check

  
